apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
        #  local:
        #    push: false
  googleCloudBuild:
    projectId: tidy-daylight-298517
  artifacts:
  - image: us.gcr.io/tidy-daylight-298517/posts
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "*.js"
        dest: .
