apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: 3028/posts
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
---        
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  selector:
    app: posts
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 4002
    name: posts
