name: deploy-auth

on:
  push:
    branches:
    - master
    paths:
    - 'posts/**'
    
jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd posts && docker build -t 3028/posts .
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push 3028/posts
    
